stages:
  - deploy

variables:
  DOCKER_BUILDKIT: "1"
  GIT_SSL_NO_VERIFY: "true"

deploy:
  stage: deploy
  image: docker:latest
  before_script:
    - apk add --no-cache docker-compose
  script:
    - docker compose -f docker-compose.yml down --remove-orphans
    - docker compose -f docker-compose.yml up -d --build
  tags:
    - etl_service
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
