stages:
  - deploy

deploy:
  stage: deploy
  image: docker:29.4-cli
  before_script:
    # из-за TLS: unspecified error при fetching APKINDEX
    - echo "https://mirrors.aliyun.com/alpine/v3.23/main" > /etc/apk/repositories
    - echo "https://mirrors.aliyun.com/alpine/v3.23/community" >> /etc/apk/repositories
    - apk add --no-cache docker-cli-compose
  script:
    - docker compose -f docker-compose.yml down --remove-orphans
    - docker compose -f docker-compose.yml up -d --build
  tags:
    - etl_service
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
