services:
  etl:
    container_name: etl-service
    build: .
    restart: unless-stopped
    environment:
      - DB_PATH=${DB_PATH}
      - API_BASE_URL=${API_BASE_URL}
      - X_INTERNAL_TOKEN=${X_INTERNAL_TOKEN}
      - HTTP_ADDR=${HTTP_ADDR}

      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}

      - PAYMENT_CH_TABLE_NAME=${PAYMENT_CH_TABLE_NAME}
      - YOO_PAYMENT_CH_TABLE_NAME=${YOO_PAYMENT_CH_TABLE_NAME}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        compress: "true"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://${HTTP_ADDR}/health"]
      interval: 5m
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - /home/user/Dev/etl-service/db:/db
    networks:
      - etl_service_main

networks:
  etl_service_main:
    driver: bridge
